- name: "Installing python-pymysql"
  apt: 
    pkg: python-pymysql

- name: Copy database .sql file
  copy:
    src: /home/upm/practica/cfg_files/data.sql
    dest: /tmp

- name: Restore database
  mysql_db:
    name: quiz
    state: import
    target: /tmp/data.sql
    login_user: quiz
    login_password: xxxx
